default: prod

environments:
  qa:
    base_url: "http://automationpractice.com/index.php"
    browser: "firefox"
  prod:
    base_url: "https://katalon-demo-cura.herokuapp.com/"
    browser: "chrome"
  user:
    base_url: "http://youtube.com"
    browser : "edge"